name: Deploy Commands

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Deploy-Commands:
    runs-on: ubuntu-latest # 22.04 bionic
    env:
      TOKEN:    ${{ secrets.TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      GUILD_ID:  ${{ secrets.GUILD_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: |
             echo "{ \
             \"token\" : \"${TOKEN}\", \
             \"clientId\" : \"${CLIENT_ID}\", \
             \"guildId\" : \"${GUILD_ID}\" \
             }" \
             > auth.json
      - run: npm i
      - run: node ./discord_api/deployCommands.js